version: "3.0"

services:
  redis:
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS = "--requirepass devpswd"
    ports:
      - "127.0.0.1:6369:6379/tcp"
      - "127.0.0.1:8001:8001"
    volumes:
      - ./redis/data:/data


  rabbit-mq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=devpswd
      - RABBITMQ_DEFAULT_VHOST=db0
    ports:
      - "5672:5672"
      - "15672:15672"
